import Navbar from "../Navbar";
import InboxButtons from "../Buttons/InboxButtons";
import React, { useState } from 'react';
import '../css/Adjudication.css';
import ActualForm from "./ActualForm";

function AdjudicationForm() {
    const [selectedCategory, setSelectedCategory] = useState('inbox');
    const [showForm, setShowForm] = useState(false); // State to manage form visibility

    const handleCategorySelect = (category) => {
        setSelectedCategory(category);
    };

    const handleReplyButtonClick = () => {
        setShowForm(true); // Set showForm to true when Reply button is clicked
    };

    return (
        <div>
            <Navbar />
            <div className="container-fluid">
                <div className="row mt-4">
                    <div className="col d-flex align-items-center justify-content-center mt-4">
                        <p className="h1 text-uppercase text-black fw-bold">seller response</p>
                    </div>
                </div>
                <div className="row">
                    <div className='col-1'></div>
                    <div className="col-2">
                        <InboxButtons onSelectCategory={handleCategorySelect} selectedCategory={selectedCategory} />
                    </div>
                    <div className='col-9'>
                        <div className="row mt-4">
                            <p className="desc">
                                <p className="h1 email-heading mt-3">Product Remediated To Comply With Recall</p>
                                <div className="row mt-3">
                                    <p className="h6 email-sender col-4">Kevin Brown &lt; kevbrown@gmail.com &gt;</p>
                                    <div className="col-4"></div>
                                    <div className="col-4 d-flex align-items-center" style={{ textAlign: 'right' }}>
                                        <p className="h6 email-sender">10:05</p>
                                        <button className="email-btn" onClick={handleReplyButtonClick}>favorite</button>
                                        <button className="email-btn" onClick={handleReplyButtonClick}>reply</button>
                                    </div>
                                </div>
                                <div className="row mt-5">
                                    <p className="email-body">This is an autogenerated message to alert you that the seller has made an update on the status of their product.</p>
                                </div>
                            </p>
                        </div>
                        <div className="row">
                            {showForm && <ActualForm />}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default AdjudicationForm;
